instance:
  _target_: models.network.ElitNet
  in_channels : 3
  dataset_classes : ${dataset.num_classes}
  layers : [16,32,64,128]
  kernel_sz : 3 
  up_mode : 'pixelshuffle'  
  conv_bridge : True 
  shortcut : True
  bottleneck_factor: 4
  num_repetitions: 2