instance:
  _target_: models.network.ElitNet.ElitNet
  in_channels : ${dataset.num_channels}
  num_classes : ${dataset.num_classes}
  layers : [4,8,16]
  kernel_sz : 3 
  up_mode : 'pixelshuffle'   #Options: 'transpose','pixelshuffle','up_conv'
  pool: 'pool'    #Options: 'pool','strided_conv','avg_pool','max_pool'
  conv_bridge : True 
  shortcut : True
  skip_conn: True 
  residual: True 
  causal: False
  conv_mode: 'Conv2d'   #Options:('Conv2d', 'MKConv2D', 'DecomConv2D', 'SeparableConv2d')

