instance:
  _target_: models.network.Unext.UNext
  num_classes : ${dataset.num_classes}
  input_channels: 3 
  deep_supervision: False
  img_size: 512 #Hardcoded Image size with for cholec
  patch_size: 16 
  in_chans: 3
  embed_dims: [128, 160, 256]
  num_heads: [1, 2, 4, 8] 
  mlp_ratios: [4, 4, 4, 4] 
  qkv_bias: False 
  qk_scale: None 
  drop_rate: 0
  attn_drop_rate: 0 
  drop_path_rate: 0 
  depths: [1, 1, 1] 
  sr_ratios: [8, 4, 2, 1]