name: brats3D
is_3d: True
global_batch_size: 1
img_size: [128, 128, 128]  # d x h x w
num_channels: 2
num_classes: 4
ignore_index: ~
class_names: ['BG','WT','EN','ET']
mean_per_channel: [476.9169, 281.4515]
std_per_channel: [1058.0099, 1036.7290]
multi_label: False
dry_run: False
cls_weights:  [0.00995578 ,0.9448299, 1.06201258, 9.19234983]

train_dataset:
  _partial_: false
  _target_: data.data3d.Dataset3D
  root_dir: ${data_dir}/Brats_3d_128
  split: train
  target_depth: 128
  target_height: 128
  target_width: 128
  extraction_mode: center
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
  dry_run: ${..dry_run}

val_dataset:
  _partial_: false
  _target_: data.data3d.Dataset3D
  root_dir: ${data_dir}/Brats_3d_128
  split: val
  target_depth: 128
  target_height: 128
  target_width: 128
  extraction_mode: center
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
  dry_run: ${..dry_run}

test_dataset:
  _partial_: false
  _target_: data.data3d.Dataset3D
  root_dir: ${data_dir}/Brats_3d_128
  split: test
  target_depth: 128
  target_height: 128
  target_width: 128
  extraction_mode: center
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
  dry_run: ${..dry_run}