name: Cataracts
global_batch_size: 8
img_size: [360, 640]
train_im_size: [384, 640]
num_channels: 3
num_classes: 11 #TODO: Only the subset that we have taken total number of classes - 36
ignore_index: ~
class_names: ['bg','pupil', 'cornea', 'skin', 'iris', 'surgical_instrument', 'hand', 'speculum', 'other_instruments', 'lens', 'background', 'misc']
mean_per_channel: [0.30843202, 0.26594361, 0.21238147]
std_per_channel: [0.30274876, 0.23929678, 0.20821963]
multi_label: False
dry_run: False
cls_weights: [1.44005782e-02, 6.65201948e+00, 1.00000000e+00, 4.35970199e+01,
 1.36072862e+01, 2.61770459e+00, 2.00894792e-01, 9.98245199e-01,
 2.15347491e-01, 6.16941872e+00, 6.80057322e-01]


train_dataset:
  _partial_: false
  _target_: data.data.SEGDataset
  root_dir: ${data_dir}/Cataracts/
  split: train
  img_size : ${..img_size}
  multi_label: ${..multi_label}
  dry_run: ${..dry_run}
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}

val_dataset:
  _partial_: false
  _target_: data.data.SEGDataset
  root_dir: ${data_dir}/Cataracts/
  split: val
  img_size : ${..img_size}
  multi_label: ${..multi_label}
  dry_run: ${..dry_run}
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}

test_dataset:
  _partial_: false
  _target_: data.data.SEGDataset
  root_dir: ${data_dir}/Cataracts/
  split: val
  img_size : ${..img_size}
  multi_label: ${..multi_label}
  dry_run: ${..dry_run}
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
