name: Cholec
global_batch_size: 8
img_size: [480, 854]  # h x w
train_im_size: [512, 896]
num_channels: 3
num_classes: 12
ignore_index: ~
class_names: ["Black Background","Abdominal Wall","Liver",
            "Gastrointestinal Tract","Fat","Grasper","Connective Tissue",
            "Blood","Cystic Duct","L-hook Electrocautery",
            "Gallbladder","Hepatic Vein"]
mean_per_channel: [0.3782772, 0.23324355, 0.22724209]
std_per_channel: [0.27367861, 0.23258302, 0.21778946]
multi_label: False
dry_run: False
cls_weights:  [
    3.07611788e-01, 2.79015445e+03, 3.25865581e+00, 5.79923131e-01,
    8.38769630e-01, 1.92239589e-01, 1.15761036e+00, 7.04655605e-01,
    8.80164325e-01, 3.56306789e+00, 1.83491041e+00, 1.67977953e+01
]

train_dataset:
  _partial_: false
  _target_: data.data.SEGDataset
  root_dir: ${data_dir}/Cholec8k/
  split: train
  img_size : ${..img_size}
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
  multi_label: ${..multi_label}
  dry_run: ${..dry_run}

val_dataset:
  _partial_: false
  _target_: data.data.SEGDataset
  root_dir: ${data_dir}/Cholec8k/
  split: val
  img_size : ${..img_size}
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
  multi_label: ${..multi_label}
  dry_run: ${..dry_run}

test_dataset:
  _partial_: false
  _target_: data.data.SEGDataset
  root_dir: ${data_dir}/Cholec8k/
  split: test
  img_size : ${..img_size}
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
  multi_label: ${..multi_label}
  dry_run: ${..dry_run}
