name: Cholec
global_batch_size: 24
img_size: [480, 854]
num_channels: 3
num_classes: 13
ignore_index: 0
class_names: ["Black Background","Abdominal Wall","Liver",
            "Gastrointestinal Tract","Fat","Grasper","Connective Tissue",
            "Blood","Cystic Duct","L-hook Electrocautery",
            "Gallbladder","Hepatic Vein","Liver Ligament"]
mean_per_channel: [0.3782772, 0.23324355, 0.22724209]
std_per_channel: [0.27367861, 0.23258302, 0.21778946]
multi_label: False
dry_run: False


train_dataset:
  _partial_: false
  _target_: data.data.SEGDataset
  root_dir: ${data_dir}/Cholec/
  split: train
  img_size : ${..img_size}
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
  multi_label: ${..multi_label}
  dry_run: ${..dry_run}

val_dataset:
  _partial_: false
  _target_: data.data.SEGDataset
  root_dir: ${data_dir}/Cholec/
  split: val
  img_size : ${..img_size}
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
  multi_label: ${..multi_label}
  dry_run: ${..dry_run}

test_dataset:
  _partial_: false
  _target_: data.data.SEGDataset
  root_dir: ${data_dir}/Cholec/
  split: test
  img_size : ${..img_size}
  mean: ${..mean_per_channel}
  std: ${..std_per_channel}
  multi_label: ${..multi_label}
  dry_run: ${..dry_run}
