devices: 2 #In order to force it to use a particular GPU, use "2" or just specify [2] check the link below
num_workers: 8
progress_bar_refresh_rate: 2
sync_batchnorm: False
accelerator: gpu
precision: 16-mixed
strategy: ddp_find_unused_parameters_true #Set to auto when on Single GPU
num_nodes: 1


#https://pytorch-lightning.readthedocs.io/en/0.9.0/multi_gpu.html#:~:text=The%20table%20below%20lists%20examples%20of%20possible%20input%20formats%20and%20how%20they%20are%20interpreted%20by%20Lightning.%20Note%20in%20particular%20the%20difference%20between%20gpus%3D0%2C%20gpus%3D%5B0%5D%20and%20gpus%3D%E2%80%9D0%E2%80%9D.